# Generated by Django 4.2.6 on 2023-10-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avadocApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avadoc',
            fields=[
                ('id_avadoc', models.AutoField(primary_key=True, serialize=False)),
                ('assid_avadoc', models.CharField(blank=True, max_length=200, null=True)),
                ('pont_avadoc', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_avadoc', models.CharField(blank=True, max_length=200, null=True)),
                ('realiza_avadoc', models.CharField(blank=True, max_length=200, null=True)),
                ('avaliacao_avadoc', models.CharField(blank=True, max_length=200, null=True)),
                ('postura_avadoc', models.CharField(blank=True, max_length=200, null=True)),
                ('id_docente', models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadocApp.docente')),
            ],
        ),
    ]
