# Generated by Django 4.2.6 on 2023-11-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avadocApp', '0002_avadoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='avadoc',
            name='id_doc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
